// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrlhlepblkwwpcappaop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ybGhsZXBibGt3d3BjYXBwYW9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTE5NzcsImV4cCI6MjA2MzkyNzk3N30.rt9ef4o7VhXIrSZS_4i5Jgq2jbHLU1TPTNaI5DoH5Cg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);